CREATE DATABASE TECHFIT_DB;
USE TECHFIT_DB;

CREATE TABLE PROFESSORES (
	ID_PROFESSOR INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PROFESSOR VARCHAR(80) NOT NULL,
    CPF VARCHAR(14),
	ESPECIALIDADE VARCHAR(80) NOT NULL
);

CREATE TABLE AULAS (
    ID_AULA INT AUTO_INCREMENT PRIMARY KEY,
    NOME_AULA VARCHAR(50),
    AVALIACAO VARCHAR(80) NOT NULL
);

	CREATE TABLE PLANOS (
		ID_PLANO INT AUTO_INCREMENT PRIMARY KEY,
		TIPO_PLANO VARCHAR(50) NOT NULL,
        DESCRICAO VARCHAR(255) NOT NULL,
        MAQUINAS VARCHAR(50) NOT NULL,
        AULAS_GRUPO VARCHAR(50) NOT NULL,
        TREINAMENTO VARCHAR(50) NOT NULL,
        CONSULTORIA VARCHAR(50) NOT NULL,
        T_AVALIACAO VARCHAR(50) NOT NULL,
        H_ACESSO VARCHAR(50) NOT NULL,
		PRECO DECIMAL(5,2) NOT NULL
);
    
CREATE TABLE ALUNOS (
	ID_ALUNO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_ALUNO VARCHAR(80) NOT NULL,
    IDADE DATE NOT NULL,
    ENDERECO_ALUNO VARCHAR(80) NOT NULL,
    TELEFONE VARCHAR(19),
    EMAIL VARCHAR(50) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    FK_PLANO INT NULL,
    FOREIGN KEY (FK_PLANO) REFERENCES PLANOS(ID_PLANO)
);

CREATE TABLE AVALIACOES_FISICAS (
    ID_AVALIACAO INT AUTO_INCREMENT PRIMARY KEY,
    DATA_AVALIACAO DATE NOT NULL,
    PESO DECIMAL(5,2) NOT NULL,
    ALTURA DECIMAL(4,2) NOT NULL,
    PEITORAL DECIMAL(5,2),
    CINTURA DECIMAL(5,2),
    QUADRIL DECIMAL(5,2),
    BRAÇO_ESQUERDO DECIMAL(5,2),
    BRAÇO_DIREITO DECIMAL(5,2),
    COXA DECIMAL(5,2),
    GORDURA_CORPORAL DECIMAL(5,2),
    MASSA_MEGRA DECIMAL(5,2),
    TMB DECIMAL(5,2),
    IMC DECIMAL(4,2),
    FK_ALUNO INT,
    FOREIGN KEY (FK_ALUNO) REFERENCES ALUNOS(ID_ALUNO)
);

CREATE TABLE FILIAS (
	ID_FILIAL INT AUTO_INCREMENT PRIMARY KEY,
    ENDERECO VARCHAR(100) NOT NULL,
    CARGA_MAX INT DEFAULT 50,
    NUM_COLABORADORES INT DEFAULT 0,
    CEP VARCHAR(15) NOT NULL
);

CREATE TABLE PRODUTOS (
	ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PRODUTO VARCHAR(80) NOT NULL,
    QUANTIDADE INT DEFAULT 20,
    PSTATUS VARCHAR(13) DEFAULT 'DISPONÍVEL',
    PRECO DECIMAL(5,2)
);

CREATE TABLE ADMINISTRACAO(
	ID_ADMINISTRADOR INT AUTO_INCREMENT PRIMARY KEY,
    SENHA VARCHAR(20) NOT NULL,
    AUSER VARCHAR(80) NOT NULL
);

CREATE TABLE RELATORIOS (
	ID_RELATORIO INT AUTO_INCREMENT PRIMARY KEY,
    RELATORIO_FILIAS VARCHAR(255),
    RELATORIO_PROFESSOR VARCHAR(255),
    RELATORIO_AULA VARCHAR(255),
    RELATORIO_CLIENTE VARCHAR(255),
    FK_FILIAL INT,
    FOREIGN KEY (FK_FILIAL) REFERENCES FILIAS(ID_FILIAL)
);

CREATE TABLE PODE (
    FK_PROFESSOR INT,
    FK_AULA INT,
    FOREIGN KEY(FK_PROFESSOR) REFERENCES PROFESSORES(ID_PROFESSOR),
    FOREIGN KEY(FK_AULA) REFERENCES AULAS(ID_AULA)
);

 CREATE TABLE POSSUI (
    FK_FILIAL INT,
    FK_PROFESSOR INT, 
    FOREIGN KEY (FK_FILIAL) REFERENCES FILIAS (ID_FILIAL),
    FOREIGN KEY (FK_PROFESSOR) REFERENCES PROFESSORES (ID_PROFESSOR)
 );

 CREATE TABLE TEM (
    FK_AULA INT,
    FK_ALUNO INT,
    FOREIGN KEY (FK_AULA) REFERENCES AULAS (ID_AULA),
    FOREIGN KEY (FK_ALUNO) REFERENCES ALUNOS (ID_ALUNO)
 );

 CREATE TABLE GERENCIA(
    FK_FILIAL INT,
    FK_RELATORIO INT,
    FK_ADMINISTRADOR INT,
    FOREIGN KEY (FK_FILIAL) REFERENCES FILIAS (ID_FILIAL),
    FOREIGN KEY (FK_RELATORIO) REFERENCES RELATORIOS (ID_RELATORIO),
    FOREIGN KEY (FK_ADMINISTRADOR) REFERENCES ADMINISTRACAO (ID_ADMINISTRADOR)
 );

 CREATE TABLE TREINA (
    FK_FILIAL INT,
    FK_RELATORIO INT,
    FK_ALUNO INT,
    FOREIGN KEY (FK_FILIAL) REFERENCES FILIAS (ID_FILIAL),
    FOREIGN KEY (FK_RELATORIO) REFERENCES RELATORIOS (ID_RELATORIO),
    FOREIGN KEY (FK_ALUNO) REFERENCES ALUNOS (ID_ALUNO)
 );

 CREATE TABLE PARTICIPA (
    FK_AULA INT,
    FK_FILIAL INT,
    FK_RELATORIO INT,
    FOREIGN KEY (FK_AULA) REFERENCES AULAS (ID_AULA),
    FOREIGN KEY (FK_FILIAL) REFERENCES FILIAS (ID_FILIAL),
    FOREIGN KEY (FK_RELATORIO) REFERENCES RELATORIOS (ID_RELATORIO)
 );